# Generated by Django 5.2.15 on 2026-07-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
